################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/vibration\ test123/liclinometer/Drivers/BSP/Components/hts221/hts221.c \
D:/vibration\ test123/liclinometer/Drivers/BSP/Components/hts221/hts221_reg.c \
D:/vibration\ test123/liclinometer/Drivers/BSP/Components/lis2dw12/lis2dw12.c \
D:/vibration\ test123/liclinometer/Drivers/BSP/Components/lis2dw12/lis2dw12_reg.c \
D:/vibration\ test123/liclinometer/Drivers/BSP/Components/lis2mdl/lis2mdl.c \
D:/vibration\ test123/liclinometer/Drivers/BSP/Components/lis2mdl/lis2mdl_reg.c \
D:/vibration\ test123/liclinometer/Drivers/BSP/Components/lps22hh/lps22hh.c \
D:/vibration\ test123/liclinometer/Drivers/BSP/Components/lps22hh/lps22hh_reg.c \
D:/vibration\ test123/liclinometer/Drivers/BSP/Components/lsm6dso/lsm6dso.c \
D:/vibration\ test123/liclinometer/Drivers/BSP/Components/lsm6dso/lsm6dso_reg.c \
D:/vibration\ test123/liclinometer/Drivers/BSP/Components/stts751/stts751.c \
D:/vibration\ test123/liclinometer/Drivers/BSP/Components/stts751/stts751_reg.c 

OBJS += \
./Drivers/BSP/Components/hts221.o \
./Drivers/BSP/Components/hts221_reg.o \
./Drivers/BSP/Components/lis2dw12.o \
./Drivers/BSP/Components/lis2dw12_reg.o \
./Drivers/BSP/Components/lis2mdl.o \
./Drivers/BSP/Components/lis2mdl_reg.o \
./Drivers/BSP/Components/lps22hh.o \
./Drivers/BSP/Components/lps22hh_reg.o \
./Drivers/BSP/Components/lsm6dso.o \
./Drivers/BSP/Components/lsm6dso_reg.o \
./Drivers/BSP/Components/stts751.o \
./Drivers/BSP/Components/stts751_reg.o 

C_DEPS += \
./Drivers/BSP/Components/hts221.d \
./Drivers/BSP/Components/hts221_reg.d \
./Drivers/BSP/Components/lis2dw12.d \
./Drivers/BSP/Components/lis2dw12_reg.d \
./Drivers/BSP/Components/lis2mdl.d \
./Drivers/BSP/Components/lis2mdl_reg.d \
./Drivers/BSP/Components/lps22hh.d \
./Drivers/BSP/Components/lps22hh_reg.d \
./Drivers/BSP/Components/lsm6dso.d \
./Drivers/BSP/Components/lsm6dso_reg.d \
./Drivers/BSP/Components/stts751.d \
./Drivers/BSP/Components/stts751_reg.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/BSP/Components/hts221.o: D:/vibration\ test123/liclinometer/Drivers/BSP/Components/hts221/hts221.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WL55xx -c -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionTL2_Library/Inc" -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionEC_Library/Inc" -I../MEMS/App -I../MEMS/Target -I../Core/Inc -I../../Drivers/BSP/custom -I../../Drivers/BSP/Components/lsm6dso -I../../Drivers/BSP/Components/lis2dw12 -I../../Drivers/BSP/Components/lis2mdl -I../../Drivers/BSP/Components/hts221 -I../../Drivers/BSP/Components/lps22hh -I../../Drivers/BSP/Components/stts751 -I../../Drivers/BSP/IKS01A3 -I../../Drivers/BSP/Components/Common -I../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../Drivers/CMSIS/Include -Oz -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Drivers/BSP/Components/hts221.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/BSP/Components/hts221_reg.o: D:/vibration\ test123/liclinometer/Drivers/BSP/Components/hts221/hts221_reg.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WL55xx -c -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionTL2_Library/Inc" -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionEC_Library/Inc" -I../MEMS/App -I../MEMS/Target -I../Core/Inc -I../../Drivers/BSP/custom -I../../Drivers/BSP/Components/lsm6dso -I../../Drivers/BSP/Components/lis2dw12 -I../../Drivers/BSP/Components/lis2mdl -I../../Drivers/BSP/Components/hts221 -I../../Drivers/BSP/Components/lps22hh -I../../Drivers/BSP/Components/stts751 -I../../Drivers/BSP/IKS01A3 -I../../Drivers/BSP/Components/Common -I../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../Drivers/CMSIS/Include -Oz -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Drivers/BSP/Components/hts221_reg.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/BSP/Components/lis2dw12.o: D:/vibration\ test123/liclinometer/Drivers/BSP/Components/lis2dw12/lis2dw12.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WL55xx -c -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionTL2_Library/Inc" -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionEC_Library/Inc" -I../MEMS/App -I../MEMS/Target -I../Core/Inc -I../../Drivers/BSP/custom -I../../Drivers/BSP/Components/lsm6dso -I../../Drivers/BSP/Components/lis2dw12 -I../../Drivers/BSP/Components/lis2mdl -I../../Drivers/BSP/Components/hts221 -I../../Drivers/BSP/Components/lps22hh -I../../Drivers/BSP/Components/stts751 -I../../Drivers/BSP/IKS01A3 -I../../Drivers/BSP/Components/Common -I../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../Drivers/CMSIS/Include -Oz -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Drivers/BSP/Components/lis2dw12.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/BSP/Components/lis2dw12_reg.o: D:/vibration\ test123/liclinometer/Drivers/BSP/Components/lis2dw12/lis2dw12_reg.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WL55xx -c -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionTL2_Library/Inc" -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionEC_Library/Inc" -I../MEMS/App -I../MEMS/Target -I../Core/Inc -I../../Drivers/BSP/custom -I../../Drivers/BSP/Components/lsm6dso -I../../Drivers/BSP/Components/lis2dw12 -I../../Drivers/BSP/Components/lis2mdl -I../../Drivers/BSP/Components/hts221 -I../../Drivers/BSP/Components/lps22hh -I../../Drivers/BSP/Components/stts751 -I../../Drivers/BSP/IKS01A3 -I../../Drivers/BSP/Components/Common -I../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../Drivers/CMSIS/Include -Oz -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Drivers/BSP/Components/lis2dw12_reg.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/BSP/Components/lis2mdl.o: D:/vibration\ test123/liclinometer/Drivers/BSP/Components/lis2mdl/lis2mdl.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WL55xx -c -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionTL2_Library/Inc" -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionEC_Library/Inc" -I../MEMS/App -I../MEMS/Target -I../Core/Inc -I../../Drivers/BSP/custom -I../../Drivers/BSP/Components/lsm6dso -I../../Drivers/BSP/Components/lis2dw12 -I../../Drivers/BSP/Components/lis2mdl -I../../Drivers/BSP/Components/hts221 -I../../Drivers/BSP/Components/lps22hh -I../../Drivers/BSP/Components/stts751 -I../../Drivers/BSP/IKS01A3 -I../../Drivers/BSP/Components/Common -I../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../Drivers/CMSIS/Include -Oz -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Drivers/BSP/Components/lis2mdl.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/BSP/Components/lis2mdl_reg.o: D:/vibration\ test123/liclinometer/Drivers/BSP/Components/lis2mdl/lis2mdl_reg.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WL55xx -c -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionTL2_Library/Inc" -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionEC_Library/Inc" -I../MEMS/App -I../MEMS/Target -I../Core/Inc -I../../Drivers/BSP/custom -I../../Drivers/BSP/Components/lsm6dso -I../../Drivers/BSP/Components/lis2dw12 -I../../Drivers/BSP/Components/lis2mdl -I../../Drivers/BSP/Components/hts221 -I../../Drivers/BSP/Components/lps22hh -I../../Drivers/BSP/Components/stts751 -I../../Drivers/BSP/IKS01A3 -I../../Drivers/BSP/Components/Common -I../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../Drivers/CMSIS/Include -Oz -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Drivers/BSP/Components/lis2mdl_reg.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/BSP/Components/lps22hh.o: D:/vibration\ test123/liclinometer/Drivers/BSP/Components/lps22hh/lps22hh.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WL55xx -c -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionTL2_Library/Inc" -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionEC_Library/Inc" -I../MEMS/App -I../MEMS/Target -I../Core/Inc -I../../Drivers/BSP/custom -I../../Drivers/BSP/Components/lsm6dso -I../../Drivers/BSP/Components/lis2dw12 -I../../Drivers/BSP/Components/lis2mdl -I../../Drivers/BSP/Components/hts221 -I../../Drivers/BSP/Components/lps22hh -I../../Drivers/BSP/Components/stts751 -I../../Drivers/BSP/IKS01A3 -I../../Drivers/BSP/Components/Common -I../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../Drivers/CMSIS/Include -Oz -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Drivers/BSP/Components/lps22hh.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/BSP/Components/lps22hh_reg.o: D:/vibration\ test123/liclinometer/Drivers/BSP/Components/lps22hh/lps22hh_reg.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WL55xx -c -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionTL2_Library/Inc" -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionEC_Library/Inc" -I../MEMS/App -I../MEMS/Target -I../Core/Inc -I../../Drivers/BSP/custom -I../../Drivers/BSP/Components/lsm6dso -I../../Drivers/BSP/Components/lis2dw12 -I../../Drivers/BSP/Components/lis2mdl -I../../Drivers/BSP/Components/hts221 -I../../Drivers/BSP/Components/lps22hh -I../../Drivers/BSP/Components/stts751 -I../../Drivers/BSP/IKS01A3 -I../../Drivers/BSP/Components/Common -I../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../Drivers/CMSIS/Include -Oz -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Drivers/BSP/Components/lps22hh_reg.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/BSP/Components/lsm6dso.o: D:/vibration\ test123/liclinometer/Drivers/BSP/Components/lsm6dso/lsm6dso.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WL55xx -c -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionTL2_Library/Inc" -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionEC_Library/Inc" -I../MEMS/App -I../MEMS/Target -I../Core/Inc -I../../Drivers/BSP/custom -I../../Drivers/BSP/Components/lsm6dso -I../../Drivers/BSP/Components/lis2dw12 -I../../Drivers/BSP/Components/lis2mdl -I../../Drivers/BSP/Components/hts221 -I../../Drivers/BSP/Components/lps22hh -I../../Drivers/BSP/Components/stts751 -I../../Drivers/BSP/IKS01A3 -I../../Drivers/BSP/Components/Common -I../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../Drivers/CMSIS/Include -Oz -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Drivers/BSP/Components/lsm6dso.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/BSP/Components/lsm6dso_reg.o: D:/vibration\ test123/liclinometer/Drivers/BSP/Components/lsm6dso/lsm6dso_reg.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WL55xx -c -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionTL2_Library/Inc" -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionEC_Library/Inc" -I../MEMS/App -I../MEMS/Target -I../Core/Inc -I../../Drivers/BSP/custom -I../../Drivers/BSP/Components/lsm6dso -I../../Drivers/BSP/Components/lis2dw12 -I../../Drivers/BSP/Components/lis2mdl -I../../Drivers/BSP/Components/hts221 -I../../Drivers/BSP/Components/lps22hh -I../../Drivers/BSP/Components/stts751 -I../../Drivers/BSP/IKS01A3 -I../../Drivers/BSP/Components/Common -I../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../Drivers/CMSIS/Include -Oz -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Drivers/BSP/Components/lsm6dso_reg.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/BSP/Components/stts751.o: D:/vibration\ test123/liclinometer/Drivers/BSP/Components/stts751/stts751.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WL55xx -c -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionTL2_Library/Inc" -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionEC_Library/Inc" -I../MEMS/App -I../MEMS/Target -I../Core/Inc -I../../Drivers/BSP/custom -I../../Drivers/BSP/Components/lsm6dso -I../../Drivers/BSP/Components/lis2dw12 -I../../Drivers/BSP/Components/lis2mdl -I../../Drivers/BSP/Components/hts221 -I../../Drivers/BSP/Components/lps22hh -I../../Drivers/BSP/Components/stts751 -I../../Drivers/BSP/IKS01A3 -I../../Drivers/BSP/Components/Common -I../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../Drivers/CMSIS/Include -Oz -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Drivers/BSP/Components/stts751.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/BSP/Components/stts751_reg.o: D:/vibration\ test123/liclinometer/Drivers/BSP/Components/stts751/stts751_reg.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WL55xx -c -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionTL2_Library/Inc" -I"C:/Users/User/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-MEMS1/11.2.0/Middlewares/ST/STM32_MotionEC_Library/Inc" -I../MEMS/App -I../MEMS/Target -I../Core/Inc -I../../Drivers/BSP/custom -I../../Drivers/BSP/Components/lsm6dso -I../../Drivers/BSP/Components/lis2dw12 -I../../Drivers/BSP/Components/lis2mdl -I../../Drivers/BSP/Components/hts221 -I../../Drivers/BSP/Components/lps22hh -I../../Drivers/BSP/Components/stts751 -I../../Drivers/BSP/IKS01A3 -I../../Drivers/BSP/Components/Common -I../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../Drivers/CMSIS/Include -Oz -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Drivers/BSP/Components/stts751_reg.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

clean: clean-Drivers-2f-BSP-2f-Components

clean-Drivers-2f-BSP-2f-Components:
	-$(RM) ./Drivers/BSP/Components/hts221.cyclo ./Drivers/BSP/Components/hts221.d ./Drivers/BSP/Components/hts221.o ./Drivers/BSP/Components/hts221.su ./Drivers/BSP/Components/hts221_reg.cyclo ./Drivers/BSP/Components/hts221_reg.d ./Drivers/BSP/Components/hts221_reg.o ./Drivers/BSP/Components/hts221_reg.su ./Drivers/BSP/Components/lis2dw12.cyclo ./Drivers/BSP/Components/lis2dw12.d ./Drivers/BSP/Components/lis2dw12.o ./Drivers/BSP/Components/lis2dw12.su ./Drivers/BSP/Components/lis2dw12_reg.cyclo ./Drivers/BSP/Components/lis2dw12_reg.d ./Drivers/BSP/Components/lis2dw12_reg.o ./Drivers/BSP/Components/lis2dw12_reg.su ./Drivers/BSP/Components/lis2mdl.cyclo ./Drivers/BSP/Components/lis2mdl.d ./Drivers/BSP/Components/lis2mdl.o ./Drivers/BSP/Components/lis2mdl.su ./Drivers/BSP/Components/lis2mdl_reg.cyclo ./Drivers/BSP/Components/lis2mdl_reg.d ./Drivers/BSP/Components/lis2mdl_reg.o ./Drivers/BSP/Components/lis2mdl_reg.su ./Drivers/BSP/Components/lps22hh.cyclo ./Drivers/BSP/Components/lps22hh.d ./Drivers/BSP/Components/lps22hh.o ./Drivers/BSP/Components/lps22hh.su ./Drivers/BSP/Components/lps22hh_reg.cyclo ./Drivers/BSP/Components/lps22hh_reg.d ./Drivers/BSP/Components/lps22hh_reg.o ./Drivers/BSP/Components/lps22hh_reg.su ./Drivers/BSP/Components/lsm6dso.cyclo ./Drivers/BSP/Components/lsm6dso.d ./Drivers/BSP/Components/lsm6dso.o ./Drivers/BSP/Components/lsm6dso.su ./Drivers/BSP/Components/lsm6dso_reg.cyclo ./Drivers/BSP/Components/lsm6dso_reg.d ./Drivers/BSP/Components/lsm6dso_reg.o ./Drivers/BSP/Components/lsm6dso_reg.su ./Drivers/BSP/Components/stts751.cyclo ./Drivers/BSP/Components/stts751.d ./Drivers/BSP/Components/stts751.o ./Drivers/BSP/Components/stts751.su ./Drivers/BSP/Components/stts751_reg.cyclo ./Drivers/BSP/Components/stts751_reg.d ./Drivers/BSP/Components/stts751_reg.o ./Drivers/BSP/Components/stts751_reg.su

.PHONY: clean-Drivers-2f-BSP-2f-Components

